version: '2'

services:
  demonstrator:
    image: jboss/wildfly
    volumes:
      - ./build:/opt/jboss/wildfly/standalone/deployments/
    networks:
      - appnet
    ports:
      - "18080:8080"
  nginx:
    image: nginx
    volumes:
      - ./humhub:/humhub
      - ./config/site.conf:/etc/nginx/conf.d/site.conf
      - ./logs:/var/log/nginx
    networks:
      - appnet
    ports:
      - "8080:80"
  php:
    build:
      context: images/php
      args:
        - workdir=/humhub
    volumes:
      - ./humhub:/humhub
    networks:
      - appnet
  mysql:
    image: mariadb:latest
    ports:
      - "33062:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=humhub
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=humhub
      - MYSQL_PASSWORD=1234
    networks:
      - appnet

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=humhub
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=humhub
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  mariadb:
    driver: "local"
  postgres:
    driver: "local"

networks:
  appnet:
    driver: "bridge"