version: '2'

services:
  demonstrator:
    build:
      context: images/wildfly_deploy
    networks:
      - humhub
    ports:
      - "8002:8080"
  nginx:
    image: nginx
    volumes:
      - ./humhub:/humhub
      - ./config/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - humhub
    ports:
      - "8082:80"
  php:
    build:
      context: images/php
      args:
        - workdir=/humhub
    volumes:
      - ./humhub:/humhub
    networks:
      - humhub
  mysql:
    image: mariadb:latest
    ports:
      - "33062:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=humhub
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=humhub
      - MYSQL_PASSWORD=1234
    networks:
      - humhub

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=humhub
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=humhub
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - humhub

volumes:
  mariadb:
    driver: "local"
  postgres:
    driver: "local"

networks:
  humhub:
    driver: "bridge"